In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3, 4, 5]
lst

[1, 2, 3, 4, 5]

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [15]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr_2d)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
arr_reshaped = arr_2d.reshape(3, 4)
arr_reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.sum(np.arange(1, 1001))

np.int64(500500)

In [19]:
import tensorflow as tf
import cv2
import numpy as np

# بارگذاری مدل از پیش آموزش‌دیده شده (ESRGAN)
model = tf.keras.models.load_model("path_to_esrgan_model.h5")

# خواندن تصویر و تبدیل آن به آرایه numpy
image = cv2.imread("input_image.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = np.expand_dims(image, axis=0)

# افزایش کیفیت تصویر با استفاده از مدل
upscaled_image = model.predict(image)

# تبدیل تصویر به فرمت اصلی
upscaled_image = np.squeeze(upscaled_image, axis=0)
upscaled_image = np.clip(upscaled_image, 0, 255).astype(np.uint8)

# ذخیره تصویر خروجی
cv2.imwrite("upscaled_image.jpg", cv2.cvtColor(upscaled_image, cv2.COLOR_RGB2BGR))

ModuleNotFoundError: No module named 'tensorflow'

In [20]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
arr = np.arange(0, 1000, 5)
b = arr.reshape(20, 10)
b

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 195],
       [200, 205, 210, 215, 220, 225, 230, 235, 240, 245],
       [250, 255, 260, 265, 270, 275, 280, 285, 290, 295],
       [300, 305, 310, 315, 320, 325, 330, 335, 340, 345],
       [350, 355, 360, 365, 370, 375, 380, 385, 390, 395],
       [400, 405, 410, 415, 420, 425, 430, 435, 440, 445],
       [450, 455, 460, 465, 470, 475, 480, 485, 490, 495],
       [500, 505, 510, 515, 520, 525, 530, 535, 540, 545],
       [550, 555, 560, 565, 570, 575, 580, 585, 590, 595],
       [600, 605, 610, 615, 620, 625, 630, 635, 640, 645],
       [650, 655, 660, 665, 670, 675, 680, 685, 690, 695],
       [700, 705, 710, 715, 720, 725, 730, 735, 740, 745],
       [750, 755, 760, 765, 770, 775, 780, 785, 790, 795],
       [800, 805, 810, 815, 820, 825, 830, 835, 840, 845

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# جمع دو آرایه
print("Sum:", a + b)

Sum: [5 7 9]


In [14]:
lst1 = [1, 2, 3]
lst2 = [10, 20, 20, 25, 30, 40]

sum = [i + j for i, j in zip(lst1, lst2)]
(lst2[len(lst2)//2 - 1] + lst2[len(lst2)//2])/2

22.5